---
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: amym-test-auto-data
   labels:
     username: amym
     env: test
 spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: cinder-csi
   resources:
     requests:
       storage: 1Gi
