---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: amym-test-redis-deployment
   labels:
     app: amym-test-redis
     username: amym
     env: test
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: amym-test-redis
   template:
     metadata:
       labels:
         app: amym-test-redis
     spec:
       containers:
         - name: redis-app
           image: redis:7
           volumeMounts:
           - name: amym-test-auto-data
             mountPath: "/data"
       volumes:
       - name: amym-test-auto-data
         persistentVolumeClaim:
           claimName: amym-test-auto-data
