---
apiVersion: v1
kind: Service
metadata:
  name: amym-test-flask-service
  labels:
    username: amym
    env: test
spec:
  type: ClusterIP
  selector:
    app: amym-test-flask-app
  ports:
  - name: amym-test-flask-app
    port: 5000
    targetPort: 5000
